t
  "Created 2021-11-03.")

(custom-theme-set-faces
 'vscode-default-high-contrast
 '(cursor ((t (:background "#fff" :foreground "#002b36" :inverse-video t :box (:line-width 1 :color "#f38518")))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#6c71c4"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#839496" :background "#000000"))))
 '(highlight ((t (:background "#073642"))))
 '(region ((t (:background "#fff" :foreground "#000"))))
 '(shadow ((t (:foreground "#586e75"))))
 '(secondary-selection ((t (:background "#073642"))))
 '(trailing-whitespace ((t (:background "#7ca668"))))
 '(font-lock-builtin-face ((t (:weight bold :slant normal :foreground "#839496"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#7ca668" :slant normal))))
 '(font-lock-comment-face ((t (:foreground "#7ca668" :slant normal))))
 '(font-lock-constant-face ((t (:foreground "#268bd2" :weight normal))))
 '(font-lock-doc-face ((t (:foreground "#7ca668" :slant normal))))
 '(font-lock-function-name-face ((t (:foreground "#DCDCAA"))))
 '(font-lock-keyword-face ((t (:foreground "#268bd2" :weight normal))))
 '(font-lock-negation-char-face ((t (:weight bold :foreground "#b58900"))))
 '(font-lock-preprocessor-face ((t (:foreground "#268bd2"))))
 '(font-lock-regexp-grouping-backslash ((t (:weight bold :foreground "#859900"))))
 '(font-lock-regexp-grouping-construct ((t (:weight bold :foreground "#b58900"))))
 '(font-lock-string-face ((t (:foreground "#ce9178"))))
 '(font-lock-type-face ((t (:foreground "#b58900"))))
 '(font-lock-variable-name-face ((t (:foreground "#9cdcfe"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "#ff69b4" :inherit (error)))))
 '(button ((t (:underline (:color foreground-color :style line)))))
 '(link ((t (:underline t))))
 '(link-visited ((t (:weight normal :underline (:color foreground-color :style line) :foreground "#b58900"))))
 '(fringe ((t ( :foreground "#ffffff" :background "#000000" :box (:line-width 1 :color "#9CDCFE")))))
 '(header-line ((t (:underline (:color "#f38518" :style line) :overline nil :box (:line-width 1 :color "#f38518" :style unspecified) :foreground "#ffffff" :background "#000000"))))
 '(tooltip ((t (:foreground "#DEB542" :background "#7B6000" :inherit (variable-pitch)))))
 '(mode-line ((t (:background "#000" :foreground "#fff"  :overline "#9CDCFE" :underline "#9CDCFE"))))
 '(mode-line-inactive ((t (:background "#000" :foreground "#fff"  :overline "#9CDCFE" :underline "#9CDCFE"))))
 '(mode-line-buffer-id ((t (:background "black" :foreground "#ffffff"  :weight bold :overline "#f38518" :underline "#f38518" :box (:line-width 1 :color "#f38518")))))
 '(mode-line-buffer-id-inactive ((t (:background "black" :foreground "#ffffff" :weight bold ))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(isearch ((t (:weight normal :box (:line-width 2 :color "#f38518") :foreground "#000000" :background "#848484"))))
 '(isearch-fail ((t (:weight bold :foreground "#dc322f" :background "#002b36"))))
 '(lazy-highlight ((t (:box (:line-width 1 :color "#f38518")))))
 '(match ((t (:weight bold :foreground "#93a1a1" :background "#073642"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((((class color) (min-colors 89)) (:background "#333333"))))
 '(hl-line ((t (:background "black" :box (:line-width 1 :color "#f38518")))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "white"))))
 '(sp-show-pair-match-face ((t (:box (:line-width 1 :color "white")))))
 '(rainbow-delimiters-base-face ((default (:inherit nil))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "white"))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "white"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "white"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "white"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "white"))))
 '(window-divider ((t (:foreground "#9cdcfe" :width condensed))))
 '(tool-bar ((t (:background "#fff" :foreground "#000" :box (:line-width 1 :style released-button)))))
 '(window-divider-last-pixel ((t (:foreground "gray40"))))
 '(border ((t (:foreground "#9cdcfe"))))
 '(org-level-1 ((t (:foreground "#b180d7"))))
 '(org-level-2 ((t (:foreground "#4EC9B0"))))
 '(org-level-3 ((t (:foreground "#DCDCAA"))))
 '(org-level-4 ((t (:inherit (outline-4)))))
 '(org-level-5 ((t (:inherit (outline-5)))))
 '(org-level-6 ((t (:inherit (outline-6)))))
 '(org-level-7 ((t (:inherit (outline-7)))))
 '(org-level-8 ((t (:inherit (outline-8)))))
 '(custom-link ((t (:foreground "#9cdcfe" :underline t))))
 '(org-headline-todo ((((class color) (min-colors 16) (background light)) (:foreground "Red4")) (((class color) (min-colors 16) (background dark)) (:foreground "Pink2")) (((class color) (min-colors 8) (background light)) (:bold t))))
 '(org-checkbox-statistics-todo ((t (:foreground "#DBABA7"))))
 '(org-todo ((t (:inherit bold :foreground "#D8ABA7" :box (:line-width 1 :color "#D8ABA7")))))
 '(markdown-inline-code-face ((t (:foreground "#e2c08d"))))
 '(org-document-title ((t (:inherit font-lock-keyword-face :weight bold :height 1.0))))
 '(org-block ((t (:inherit nil :extend t :foreground "#b180d7"))))
 '(default ((t (:inherit nil :stipple nil :background "black" :foreground "white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 98 :width normal :foundry "PfEd" :family "DejaVu Sans Mono"))))
 '(ediff-odd-diff-A ((t (:extend t :box (:line-width 2 :color "grey75" :style released-button)))))
 '(ediff-odd-diff-B ((t (:extend t :box (:line-width 2 :color "LightGrey" :style released-button)))))
 '(ediff-odd-diff-C ((t (:extend t :box (:line-width 2 :color "Grey" :style released-button)))))
 '(ediff-fine-diff-A ((t (:box (:line-width 2 :color "#aa2222" :style released-button)))))
 '(ediff-fine-diff-B ((t (:box (:line-width 2 :color "#22aa22" :style released-button)))))
 '(ediff-fine-diff-C ((t (:box (:line-width 2 :color "#aaaa22" :style released-button)))))
 '(ediff-even-diff-A ((t (:extend t :box (:line-width 2 :color "light grey" :style released-button)))))
 '(ediff-even-diff-B ((t (:extend t :box (:line-width 2 :color "Grey" :style released-button)))))
 '(ediff-even-diff-C ((t (:extend t :box (:line-width 2 :color "light grey" :style released-button)))))
 '(ediff-current-diff-A ((t (:extend t :box (:line-width 2 :color "#553333" :style released-button)))))
 '(ediff-current-diff-B ((t (:extend t :box (:line-width 2 :color "#335533" :style released-button)))))
 '(ediff-current-diff-C ((t (:extend t :box (:line-width 2 :color "#888833" :style released-button)))))
 '(ediff-odd-diff-Ancestor ((t (:extend t :box (:line-width 2 :color "gray40" :style released-button)))))
 '(ediff-fine-diff-Ancestor ((t (:box (:line-width 2 :color "#009591" :style released-button)))))
 '(ediff-even-diff-Ancestor ((t (:extend t :box (:line-width 2 :color "Grey" :style released-button)))))
 '(ediff-current-diff-Ancestor ((t (:extend t :box (:line-width 2 :color "#004151" :style released-button)))))
 '(mu4e-unread-face ((t (:foreground "#b180d7"))))
 '(mu4e-header-face ((t (:inherit (default)))))
 '(mu4e-flagged-face ((t (:weight bold :inherit (font-lock-constant-face)))))
 '(mu4e-header-value-face ((t (:inherit (font-lock-type-face)))))
 '(mu4e-view-body-face ((t (:inherit (default)))))
 '(mu4e-header-highlight-face ((t (:box (:line-width 1 :color "#f38518")))))
 '(mu4e-header-key-face ((t (:foreground "#b180d7" :weight bold))))
 '(mu4e-header-title-face ((t (:inherit (font-lock-type-face)))))
 '(mu4e-link-face ((t (:inherit (link)))))
 '(web-mode-javascript-string-face ((t (:inherit (web-mode-string-face)))))
 '(web-mode-string-face ((t (:foreground "#ce9178"))))
 '(web-mode-javascript-comment-face ((t (:foreground "#7ca668"))))
 '(web-mode-comment-face ((t (:foreground "#7ca668"))))
 '(web-mode-html-tag-face ((t (:inherit font-lock-constant-face))))
 '(web-mode-html-tag-custom-face ((t (:inherit web-mode-html-tag-face :slant italic))))
 '(web-mode-html-attr-name-face ((t (:inherit font-lock-variable-name-face))))
 '(js2-function-param ((t (:inherit font-lock-variable-name-face))))
 '(js2-object-property ((t (:inherit font-lock-variable-name-face))))
 '(js2-object-property-access ((t (:inherit (js2-object-property)))))
 '(js2-external-variable ((t (:foreground "#4EC9B0"))))
 '(markdown-inline-code-face ((t (:foreground "#e2c08d"))))
 '(js2-function-call ((t (:inherit font-lock-function-name-face))))
 '(org-agenda-date-today ((t (:box (:line-width 2 :color "#FFFFFF" :style released-button)))))
 '(org-agenda-date ((t (:box (:line-width 2 :color "grey75" :style released-button)))))
 '(org-super-agenda-header ((t (:foreground "#b180d7"))))
 '(org-scheduled-today ((t (:foreground "#9CDCFE"))))
 '(org-upcoming-deadline ((t (:foreground "#808080"))))
)

(provide-theme 'vscode-default-high-contrast)
